### ISSUE TITLE
help setup

### ISSUE THREAD

**Issue by yaakovmargalit** [xch91/vue-scratchcard#11]
Sorry but I do not understand how to use the library,
You're importing a component from SRC
????
What should be in it?
I would love for more explanation

**Comment by alyoshark** [comment]
Oops sorry I forgot to include in README but you can either use it locally within a component file by

```javascript
import ScratchCard from 'vue-scratchcard';
```

or register globally in your js entry:

```javascript
import ScratchCard from 'vue-scratchcard';
Vue.use(ScratchCard)
```

Then in your SFC <template> you can write:

```html
<scratch-card :prop1=...></scratch-card>
``` 

Hope it helps!

**Comment by slim-python** [comment]
cmon man don't do it lol
