### ISSUE TITLE
how to excute @complete event after all cards are scratched within a div?

### ISSUE THREAD

**Issue by slim-python** [xch91/vue-scratchcard#14]
I have a total of 9 cards iterated with `v-for` when all 9 cards are fully scratched I want to alert something to the user, how do I do it?
currently when any one of the card is scratched @complete event works  

![image](https://user-images.githubusercontent.com/55599278/147658439-7c0d1f12-a845-4aaa-8817-e4694d875544.png)

**Comment by alyoshark** [comment]
The best way I can think of is wrapping each one inside a wrapper to handle the logic

**Comment by slim-python** [comment]
Instead i added a ref in scracth card component by ` <scratch-card ref="CardRef" >`
and did this 
```
  methods: {
    onComplete() {
      var CardArray = this.$refs.CardRef;
      for (var i=0; i<CardArray.length; i++) {
        console.log(CardArray[i].isDrawing);
      }
      const allTrue = CardArray.every((c) => c.isDrawing);
      if (allTrue) {
        // alert("all card is scratched");
        this.cards[0].scratched = true;
        this.HideScoreBoard = true;
      }
    }
  } 
```
