### ISSUE TITLE
mouseevent not working after scrolled

### ISSUE THREAD

**Issue by look416** [xch91/vue-scratchcard#2]
Under Firefox Android, the mouseevent for the canvas is not triggered after the page is scrolled. However it still works  well when the scroll position is at the top of the page.

**Comment by alyoshark** [comment]
That's an interesting case. I don't have Android Firefox at the moment. Will try getting one and test it soon. Can you provide the version of the Firefox that shows this issue?

**Comment by DelboyTrotter** [comment]
It's active on Chrome (desktop and mobile) too.

**Comment by alyoshark** [comment]
After looking into the code and some experiment, I realized that `event.touches[0].clientX` and `event.pageX` refer to different places in the page and need to be handled separately. It should be fixed now.
