### ISSUE TITLE
Please add method/property to hide again

### ISSUE THREAD

**Issue by stefandevo** [xch91/vue-scratchcard#4]
Great component; you now have a property to reveal; but how about a property to reset it again?

**Comment by alyoshark** [comment]
Thanks for your interest in the project!

For resetting a component, there is actually a more established way to do so from the parent component, which I can later include in README and `example/App.vue`. Basic idea is to include a `key` attribute and change it whenever a force rerendering is needed.

Here is a very elaborate post explain patterns of rerendering in detail: http://michaelnthiessen.com/force-re-render/
